### PR TITLE
Adding class name to uploader frame for unique identification

### PR DESCRIPTION
**Pull request by kvikram1988**
## Description

IFrame is an inline element. Giving just height and width without the display won't work. So, adding display property and also adding a unique className for identification.

## Motivation and Context

Multiple iframes are rendered on UI for uploads and these iframes are taking up empty space provided by default by the browser.

## How Has This Been Tested?

Tested it on ACC UI to see if IFrame is no more taking up empty space. Also classname can be seen.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by mkiki — COMMENTED** [review]
Shouldn't the class name use a random number to make it really unique?

**Comment by kvikram1988** [comment]
> Shouldn't the class name use a random number to make it really unique?

Made it configurable, taking it through the options. classNames need not be unique as it is only used for styling

**Comment by gauravmakkar** [comment]
@kvikram1988 if we want the iframe to be unique, why don't we use `id` instead?

**Comment by kvikram1988** [comment]
> @kvikram1988 if we want the iframe to be unique, why don't we use `id` instead?

@gauravmakkar We don't want iframe to be unique within same types, we want it to be unique from other iframes. Like upon 3 uploads, 3 iframes will be rendered by acc-js-sdk. We want handle those by common classname but we can't do the same with unique ids.

**Review by mkiki — APPROVED** [review]

**Pull request merged**
